# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqr', '0002_auto_20170925_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('added', 'Added'), ('excluded', 'Excluded')], default=None, max_length=16, null=True),
        ),
    ]
