# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqr', '0005_report_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='interval',
            field=models.CharField(choices=[('1days', '1 Day'), ('7days', '7 Days'), ('14days', '14 Days'), ('30days', '30 Days'), ('60days', '60 Days'), ('alltime', 'All Time')], default='alltime', max_length=50, null=True, verbose_name='Interval'),
        ),
    ]
