# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqr', '0006_report_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_cities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_countries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_states',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='interval',
            field=models.CharField(choices=[('1days', '1 Day'), ('7days', '7 Days'), ('14days', '14 Days'), ('30days', '30 Days'), ('60days', '60 Days'), ('alltime', 'All Time')], db_index=True, default='alltime', max_length=50, null=True, verbose_name='Interval'),
        ),
        migrations.AlterField(
            model_name='report',
            name='source',
            field=models.CharField(choices=[('adwords', 'AdWords'), ('bingads', 'BingAds'), ('csv', 'csv import')], db_index=True, default='adwords', max_length=255, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('added', 'Added'), ('excluded', 'Excluded')], db_index=True, default='active', max_length=16, null=True),
        ),
    ]
