# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-13 17:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='adwords_credentials',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Put here credentials.json file content', null=True, verbose_name='Credentials'),
        ),
    ]
