# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_preferences_adwords_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='adwords_client_id',
            field=models.TextField(blank=True, null=True, verbose_name='AdWords Client ID'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='adwords_client_secret',
            field=models.TextField(blank=True, null=True, verbose_name='AdWords Client Secret'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='adwords_dev_token',
            field=models.TextField(blank=True, null=True, verbose_name='AdWords Dev Token'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='adwords_manager_id',
            field=models.TextField(blank=True, null=True, verbose_name='AdWords Manager ID'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='adwords_refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='AdWords Refresh Token'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='bing_account_id',
            field=models.TextField(blank=True, null=True, verbose_name='Bing Account ID'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='bing_client_id',
            field=models.TextField(blank=True, null=True, verbose_name='Bing Client ID'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='bing_client_secret',
            field=models.TextField(blank=True, null=True, verbose_name='Bing Client Secret'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='bing_customer_id',
            field=models.TextField(blank=True, null=True, verbose_name='Bing Customer ID'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='bing_dev_token',
            field=models.TextField(blank=True, null=True, verbose_name='Bing Dev Token'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='bing_mode',
            field=models.TextField(blank=True, null=True, verbose_name='Bing mode'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='facebook_access_token',
            field=models.TextField(blank=True, null=True, verbose_name='Facebook Access Token'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='facebook_app_id',
            field=models.TextField(blank=True, null=True, verbose_name='Facebook App ID'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='facebook_app_secret',
            field=models.TextField(blank=True, null=True, verbose_name='Facebook App Secret'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='facebook_app_token',
            field=models.TextField(blank=True, null=True, verbose_name='Facebook App Token'),
        ),
    ]
