# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_auto_20180214_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='adwords_credentials',
        ),
        migrations.AlterField(
            model_name='preferences',
            name='adwords_client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AdWords Client ID'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='adwords_dev_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AdWords Dev Token'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='adwords_manager_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AdWords Manager ID'),
        ),
    ]
