# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('conversions', models.DecimalField(decimal_places=0, max_digits=16, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('source', models.CharField(blank=True, choices=[('adwords', 'Google AdWords'), ('facebookads', 'Facebook Ads'), ('bingads', 'Bing Ads')], default='adwords', max_length=255, null=True, verbose_name='Source')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='clients.Client')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
