# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='conversions',
            new_name='conversions_adwords',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='cost',
            new_name='cost_adwords',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='source',
        ),
        migrations.AddField(
            model_name='ad',
            name='conversions_bingads',
            field=models.DecimalField(decimal_places=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='conversions_facebookads',
            field=models.DecimalField(decimal_places=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='cost_bingads',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='cost_facebookads',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
    ]
