# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20170922_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='conversions_adwords',
            field=models.DecimalField(decimal_places=0, max_digits=16, null=True, verbose_name='Conversions (Adwords)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='conversions_bingads',
            field=models.DecimalField(decimal_places=0, max_digits=16, null=True, verbose_name='Conversions (BingAds)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='conversions_facebookads',
            field=models.DecimalField(decimal_places=0, max_digits=16, null=True, verbose_name='Conversions (FacebookAds)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='cost_adwords',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Cost (AdWords)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='cost_bingads',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Cost (BingAds)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='cost_facebookads',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Cost (FacebookAds)'),
        ),
    ]
