# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0007_auto_20170929_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Setup Assignment')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('order', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('n/a', 'N/A'), ('waiting', 'Waiting on Client')], max_length=255, null=True)),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, upload_to='channel_logos/', verbose_name='Logo')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
            ],
            options={
                'db_table': 'channels',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TemplateAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('status', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('n/a', 'N/A'), ('waiting', 'Waiting on Client')], max_length=255, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to='onboarding.Channel')),
            ],
            options={
                'db_table': 'template_assignments',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='onboarding.Channel'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='clients.Client', verbose_name='Client'),
        ),
    ]
