# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='onboarding.Channel'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='clients.Client', verbose_name='Client'),
        ),
    ]
