# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_auto_20170925_0720'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('impressions', models.DecimalField(db_index=True, decimal_places=6, max_digits=18, null=True, verbose_name='Impressions')),
                ('clicks', models.DecimalField(db_index=True, decimal_places=6, max_digits=18, null=True, verbose_name='Clicks')),
                ('cost', models.DecimalField(db_index=True, decimal_places=6, max_digits=18, null=True, verbose_name='Cost')),
                ('conversions', models.DecimalField(db_index=True, decimal_places=6, max_digits=18, null=True, verbose_name='Conversions')),
                ('placement', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Search Term')),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('added', 'Added'), ('excluded', 'Excluded')], default='active', max_length=16, null=True)),
                ('source', models.CharField(choices=[('adwords', 'AdWords'), ('bingads', 'BingAds'), ('csv', 'csv import')], default='adwords', max_length=255, null=True, verbose_name='Source')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pprs', to='clients.Client')),
            ],
            options={
                'db_table': 'pprs',
                'ordering': ['placement'],
            },
        ),
    ]
