# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170925_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='planned_budget_adwords',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Goal for Spend (AdWords)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='planned_budget_bingads',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Goal for Spend (BingAds)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='planned_budget_facebookads',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Goal for Spend (FacebookAds)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='planned_conversions_adwords',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Goal for Conversion (AdWords)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='planned_conversions_bingads',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Goal for Conversion (BingAds)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='planned_conversions_facebookads',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Goal for Conversion (FacebookAds)'),
        ),
    ]
