# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20170925_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='planned_cpa_adwords',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Goal for CPA (AdWords)'),
        ),
        migrations.AddField(
            model_name='client',
            name='planned_cpa_bingads',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Goal for CPA (BingAds)'),
        ),
        migrations.AddField(
            model_name='client',
            name='planned_cpa_facebookads',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Goal for CPA (FacebookAds)'),
        ),
    ]
