# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20170925_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
