# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:02
from __future__ import unicode_literals

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_google_spreadsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='google_spreadsheet',
            field=models.URLField(blank=True, null=True, validators=[clients.models.validate_google_spreadsheet_link], verbose_name='Google spreadsheet SQR'),
        ),
    ]
