# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngram',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('added', 'Added'), ('excluded', 'Excluded')], default='active', max_length=16, null=True),
        ),
    ]
